name: Run Notebooks

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.ipynb'
      - 'requirements.txt'
      - '.github/workflows/run-notebooks.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.ipynb'
      - 'requirements.txt'
      - '.github/workflows/run-notebooks.yml'

jobs:
  execute-notebooks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install papermill nbconvert nbformat
          python -m ipykernel install --user --name=python3

      - name: Lint Notebooks
        run: |
          pip install nbqa black
          nbqa black --check .

      - name: Create outputs folder
        run: mkdir -p outputs

      - name: Run all notebooks
        run: |
          set -e
          for notebook in $(find . -name "*.ipynb"); do
            echo ">>> Running $notebook"
            papermill "$notebook" "outputs/$(basename "$notebook")"
          done

      - name: Upload executed notebooks
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebooks
          path: outputs/
